# Generated by Django 4.2 on 2025-07-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0004_awsaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='allow_plain_pkce',
            field=models.BooleanField(blank=True, default=False, help_text='Allow code_challenge_method=plain for PKCE'),
        ),
        migrations.AddField(
            model_name='client',
            name='token_expiry',
            field=models.IntegerField(blank=True, help_text='Token expiration timeout. Defaults to OAUTH_EXPIRE_DELTA_PUBLIC or OAUTH_EXPIRE_DELTA', null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='code_challenge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='code_challenge_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.IntegerField(choices=[(0, 'Confidential (Web applications)'), (1, 'Public (Native and JS applications)'), (2, 'RFC7636 PKCE (Native, JS, and Web applications)')]),
        ),
    ]
