# Generated by Django 4.2 on 2025-08-17 03:13

from django.db import migrations, models
import django.db.models.deletion
import provider.utils


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0005_pkce'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=provider.utils.client_secret_description, max_length=255)),
                ('secret_first6', models.CharField(db_index=True, max_length=6)),
                ('secret_hash', models.CharField(max_length=255)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth2.client')),
            ],
            options={
                'db_table': 'oauth2_clientsecret',
            },
        ),
    ]
