# Generated by Django 4.2 on 2025-08-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0006_clientsecrets'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='token_prefix',
            field=models.CharField(db_index=True, max_length=10, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='token_prefix',
            field=models.CharField(db_index=True, max_length=10, null=True, blank=True),
        ),
    ]
